general {
    base_exp_dir = ./exp/CASE_NAME
    recording = [
        ./,
        ./models
        ./encoding
    ]
}

dataset {
    data_dir = ./public_data/CASE_NAME/CASE_NAME_normal
    render_cameras_name = cameras_sphere.npz
    object_cameras_name = cameras_sphere.npz
    exclude_views = []    # 1, 18, 26
    type = super
    normal_dir = normal_world_space_sdmunips
    height = 3360       # 原始尺寸  1440 
    width = 2240        # 1920
    exp_time_dir = CASE_NAME_close  # real_normal_metashape
    real_data = True
}

train {
    learning_rate = 5e-4
    learning_rate_alpha = 0.05
    end_iter = 70002
    increase_bindwidth_every = 350  # following neuralangelo's strategy

    batch_size = 4096
    validate_resolution_level = 1
    warm_up_end = 5000
    anneal_end = 0
    use_white_bkgd = False

    save_freq = 5000
    report_freq = 50


    igr_weight = 1
    mask_weight = 2
    normal_weight = 0.1
    sdf_weight = 10
}

val {
    val_freq = 70000        # render normal
    val_mesh_freq = 1
    eval_metric_freq = 70005    # cd/mae
    val_mesh_res = 2000

    save_freq = 10000
    val_normal_freq = 20000
    val_normal_resolution_level = 1
    gradient_method = dfd  # dfd or fd or ad, can be different from training
    
    report_freq = 100
    
}

model {
    sdf_network {
        d_out = 1,
        d_in = 3,
        d_hidden = 64,
        n_layers = 1,
        skip_in = [-1]  # -1 for no skip connection
        bias = 0.6,
        radius_min = 0.002,        # 0.0002,      
        radius_max = 0.004,        # 0.00024  buddha (diligent-)
        geometric_init = True   
        weight_norm = True
        input_concat = True  # concat input positions and encoded features
    }

    variance_network {
        init_val = 0.5
    }

    kplanes {
        aabb = [[-1, -1, -1], [1, 1, 1]],
        grid_config = [{
            grid_dimensions= 2,
            input_coordinate_dim= 3,
            output_coordinate_dim= 8,
            resolution= [32, 32, 32, 4]   # x,y,z,t的分辨率  [32, 32, 32, 128]
            }],
        concat_features_across_scales =  True,
        multiscale_res =  [1],
        density_activation = trunc_exp,
    }

    neus_renderer {
        set_radius = 0.00075
        n_samples = 64
        n_importance = 64
        n_outside = 0
        up_sample_steps = 4     # 1 for simple coarse-to-fine sampling
        perturb = 1.0
}

    encoding{
        otype=HashGrid,
		n_levels=14
		n_features_per_level=2
		log2_hashmap_size=19
		base_resolution=32
		per_level_scale=1.3195079107728942
    }
}
